sap.ui.define([
	"sap/ui/model/json/JSONModel",
	"sap/ui/Device"
], function (JSONModel, Device) {
	"use strict";
	return {
		generalData: {
			"NSTID": "",
			"NSANM": "",
			"NSART": "",
			"NINDA": 0,
			"NSTVA": 0,
			"NSTDN": "",
			"NABVF": "",
			"NSRTE": "",
			"NBTKM": "",
			"NAADS": "",
			"NAKMG": "",
			"NPJAB": "",
			"NKDWG": 0,
			"NDSTG": "",
			"NPTHC": "",
			"NDTHC": "",
			"NPCBD": "",
			"NDCBD": "",
			"NPCBN": "",
			"NDCBN": "",
			"NBART": "",
			"NBLNG": ""
		},
		Effects: {
			"NERIE": 0,
			"NKZTT": 0,
			"NGKCH": 0,
			"NEPNT": 0,
			"NEHBN": 0,
			"NMGNE": 0,
			"NSFGT": 0,
			"NMKMF": 0,
			"NSTRS": 0,
			"NSCZN": 0,
			"NSWDL": 0,
			"NTKMD": 0,
			"NTKAN": 0,
			"NKFMN": 0,
			"NPROI": 0
		},
		ProneTo: {
			"NSMBN": false,
			"NTRPS": false,
			"NRPEN": false,
			"NSPDS": false,
			"NPMCN": false,
			"NMHTU": false,
			"NWZFL": false,
			"NKSFL": false,
			"NSKFF": false,
			"NPSPR": false,
			"NKLUM": false,
			"NMGSM": false,
			"NCLCM": false,
			"NSWFL": false,
			"NBOR": false,
			"NESEN": false,
			"NZNK": false,
			"NMBN": false
		},
		Nutrient: {
			"NGSKF": "",
			"NGPPR": "",
			"NGKLM": "",
			"NGMGM": "",
			"NGCLM": "",
			"NGSWL": "",
			"NGBOR": "",
			"NGESN": "",
			"NGZNK": "",
			"NGMBN": "",
			"NFSKF": "",
			"NFPPR": "",
			"NFKLM": "",
			"NFMGM": "",
			"NFCLM": "",
			"NFSWL": "",
			"NFBOR": "",
			"NFESN": "",
			"NFZNK": "",
			"NFMBN": ""
		},
		Terpene: {
			"NPNN": "",
			"NBCPN": "",
			"NBRL": "",
			"NCPLD": "",
			"NCELE": "",
			"NCTNL": "",
			"NHMNE": "",
			"NLMEN": "",
			"NLNOL": "",
			"NMRNE": "",
			"NNROL": "",
			"NPYTL": "",
			"NTRPN": ""
		},
		Timings: {
			"NPSVG": "",
			"NDSVG": "",
			"NPKMG": "",
			"NDKMG": "",
			"NPGZT": "",
			"NDGZT": "",
			"NPBZT": "",
			"NDBZT": "",
			"NPTZT": "",
			"NDTZT": "",
			"NPAZT": "",
			"NDAZT": ""
		}

	};
});